server:
  port: 8085
spring:
  application:
    name: "messages-service"
  datasource:
    url: jdbc:mysql://localhost:3306/reservationdb
    username: root
    password: password12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    consumer:
      group-id: reservation-ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.trip.advisor.common.*"
        allow.auto.create.topics: false
      bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
      auto-offset-reset: earliest

  mail:
    host: smtp.gmail.com
    port: 587
    username: "${EMAIL}"
    password: "${PASSWORD}"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true



topic:
  messageCommand: "message-command"