FROM openjdk:21-jdk-slim

MAINTAINER tzetzaka.com

COPY target/recommendation-service-1.0-SNAPSHOT.jar recommendation-service-1.0-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "recommendation-service-1.0-SNAPSHOT.jar"]