server:
  port: 9090
spring:
  application:
    name: "events"
  datasource:
    url: jdbc:mysql://localhost:3307/eventsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

    #only if need automated reload on config files from git

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

logging:
  level:
    org.springframework.boot.actuate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"