server:
  port: 9000
spring:
  application:
    name: "events"
  datasource:
    url: jdbc:mysql://localhost:3307/eventsdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  config:
    import: "configserver:http://localhost:8071/"

    #only if need automated reload on config files from git

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

logging:
  level:
    com:
      trip:
        advisor:
          events: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "events"
    description: "Tripadvisor Events Application"
    version: "1.0.0"