FROM openjdk:21-jdk-slim

MAINTAINER tzetzaka.com

COPY target/accommodation-service-1.0-SNAPSHOT.jar accommodation-service-1.0-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "accommodation-service-1.0-SNAPSHOT.jar"]
