services:
  configserver:
    image: "tzetzaka2/configserver:s2"
    container_name: accommodation-ms
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tripadvisor
  accommodation-service:
    image: "tzetzaka2/accommodation-service:s2"
    container_name: accommodation-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tripadvisor
    environment:
      SPRING_APPLICATION_NAME: "accommodation-service"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default

  recommendation-service:
    image: "tzetzaka2/recommendation-service:s2"
    container_name: recommendation-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tripadvisor
    environment:
      SPRING_APPLICATION_NAME: "recommendation-service"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default

  events-service:
    image: "tzetzaka2/events-service:s2"
    container_name: events-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tripadvisor
    environment:
      SPRING_APPLICATION_NAME: "events-service"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default

networks:
  tripadvisor:
    driver: "bridge"