services:
#  rabbit:
#    image: rabbitmq:3.12-management
#    hostname: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    extends:
#      file: common-config.yml
#      service: network-deploy-service

  configserver:
    image: "tzetzaka2/configserver:s2"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config


  accommodation-service:
    image: "tzetzaka2/accommodation-service:s2"
    container_name: accommodation-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accommodation"
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  recommendation-service:
    image: "tzetzaka2/recommendation-service:s2"
    container_name: recommendation-ms
    ports:
      - "8090:8090"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "recommendation"


  events-service:
    image: "tzetzaka2/events-service:s2"
    container_name: events-ms
    ports:
      - "9000:9000"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "events"


networks:
  tripadvisor:
    driver: "bridge"