server:
  port: 8080
spring:
  application:
    name: "accommodation"
  datasource:
    url: jdbc:mysql://localhost:3306/accommodationdb
    username: root
    password: root
  #    h2 DATABASE
#    url: jdbc:h2:mem:accommodationdb
#    driver-class-name: org.h2.Driver
#    username: tze
#    password: ''
#  h2:
#    console:
#      enabled: true
#    h2 MYSQL DATABASE
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

    #only if need automated reload on config files from git

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

logging:
  level:
    org.springframework.boot.actuate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

