services:
  accommodationdb:
    image: mysql
    container_name: accommodationdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accommodationdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  eventsdb:
    image: mysql
    container_name: eventsdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: eventsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  recommendationdb:
    image: mysql
    container_name: recommendationdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: recommendationdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "tzetzaka2/configserver:s5"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "tzetzaka2/eurekaserver:s5"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  accommodation-service:
    image: "tzetzaka2/accommodation-service:s5"
    container_name: accommodation-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "accommodation"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accommodationdb:3306/accommodationdb"
    depends_on:
      accommodationdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  recommendation-service:
    image: "tzetzaka2/recommendation-service:s5"
    container_name: recommendation-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "recommendation"
      SPRING_DATASOURCE_URL: "jdbc:mysql://recommendationdb:3306/recommendationdb"
    depends_on:
      recommendationdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  events-service:
    image: "tzetzaka2/events-service:s5"
    container_name: events-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "events"
      SPRING_DATASOURCE_URL: "jdbc:mysql://eventsdb:3306/eventsdb"
    depends_on:
      eventsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: "tzetzaka2/gatewayserver:s5"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      accommodation-service:
        condition: service_healthy
      events-service:
        condition: service_healthy
      recommendation-service:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  tripadvisor:
    driver: "bridge"


#  rabbit:
#    image: rabbitmq:3.12-management
#    hostname: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    extends:
#      file: common-config.yml
#      service: network-deploy-service